Kan 40 implementar funcionalidades restantes para el modulo de workspaces
WillianChavez/api-fielding pull request #24
Opened 2024-08-15 14:10 UTC by epmyas2022

- [ ] Se agrego la relaciones con el modelo de usuario
- [ ] Se actualizo la respuesta de la creacion de un workspace
- [ ] Se actualizo el resource de respuesta de la lista de colaboradores
- [ ] Se agrego la validacion al crear un workspaces no existan valores repetidos
- [ ] Se cambio la estructutura del endpoint de de lista de colaboradores de query a un param

2024-08-15 20:53 UTC, WillianChavez requested changes

2024-08-15 20:53 UTC, WillianChavez commented on src/workspace/application/list-collaborator-use-case/list-collaborator.dto.ts
refactorizar a una sola interface

2024-08-16 14:10 UTC, epmyas2022 commented on src/workspace/application/list-collaborator-use-case/list-collaborator.dto.ts
:+1:

2024-08-16 15:30 UTC, WillianChavez approved these changes
👍

2024-08-16 15:30 UTC, merged