Kan 51 se requiere poder ver en tiempo real las personas que estan trabajando en un espacio de trabajo
WillianChavez/api-fielding pull request #40
Opened 2024-09-11 19:37 UTC by epmyas2022

Se agrego un evento socket para  agregar y obtener a los usuarios activos en un espacio de trabajo

Prueba del caso
![Captura desde 2024-09-12 09-01-24](https://github.com/user-attachments/assets/6e71a15a-168c-4b1c-9983-07762250110c)

2024-09-11 19:56 UTC, WillianChavez requested changes

2024-09-11 19:56 UTC, WillianChavez commented on src/resource/applitacion/join-user-active-use-case/join-user-active-use-case.ts
> +  private activesUsers: JoinUserActiveDto[] = [];
ocupar un mapa para guardar los usuarios activos

2024-09-11 19:56 UTC, WillianChavez commented on src/resource/infrastructure/real-time/gateway/gateway.socket.ts
> +
agregar evento para sacar el usuario del canal

2024-09-13 14:35 UTC, WillianChavez requested changes

2024-09-13 14:35 UTC, WillianChavez commented on src/resource/infrastructure/repositories/memory.user-active.repository.ts
> +  async create(resource: ActiveUser): Promise<ActiveUser> {
refactorizar: el metodo create solo deberia de crear o agregar en el array activesUsers según el principio de única responsabilidad, mover la logica restante a los casos de uso correspondiente

2024-09-20 17:09 UTC, willianMyneflow approved these changes
👍

2024-09-20 17:09 UTC, willianMyneflow approved these changes
👍

2024-09-20 17:10 UTC, WillianChavez approved these changes
💯

2024-09-20 17:10 UTC, merged